server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/D:\H2\db\my-project
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    #hibernate setting
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #system.out
        show_sql: true
        #format pretty
        format_sql: true

#logging
  logging:
    level:
      org.hibernate:
        # sql leverl
        sql: debug
        # sql show sql parameter
        type: trace


