spring:
  application:
    name: my-project
  profiles:
    group:
      local: local,console-logging
      dev: dev,console-logging,file-logging
      prd: prd,console-logging,file-logging

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

